### ISSUE TITLE
TracingPropagationExecInitializer searching for wrong class in registry entries.

### ISSUE THREAD

**Issue by kirenjolly** [openzipkin-contrib/brave-ratpack#14]
`init` function in TracingPropagationExecInitializer is trying to get `HttpTracing.class` from the execution object i pass but instead it should `maybeGet(TraceContextHolder.class)`.
Since in my registry entries only this is present.
```RegistryEntry{type=ratpack.zipkin.internal.RatpackCurrentTraceContext$TraceContextHolder, value=ratpack.zipkin.internal.RatpackCurrentTraceContext$TraceContextHolder@6139672b}```.
Hence httpTracing  is always null in `init`.

So `init` can't be used for manual setting of TraceContext on passing the current `Execution` because at that point `RatpackCurrentTraceContext$TraceContextHolder` will be having the `CurrentTraceContext` and not `HttpTracing.class`

**Comment by kirenjolly** [comment]
@devinsba @llinder Please Correct me if i am wrong. Because this function(`init`) is what we are using as a workaround for context propagation in ratpack promises and async calls

**Comment by kirenjolly** [comment]
I can raise a PR for that change too.

**Comment by codefromthecrypt** [comment]
can you raise a pull request? it looks like you know where the problem might be

**Comment by codefromthecrypt** [comment]
basically if you can put a test that fails until a change is made.. and also that change. it will be a great way of unblocking yourself :P

**Comment by kirenjolly** [comment]
Yeah i will create a test for both the cases and raise a PR for that.
