### ISSUE TITLE
Add .mailmap file

### ISSUE THREAD

**Issue by kirenjolly** [openzipkin-contrib/brave-ratpack#16]
Add .mailmap file to map commits to correct email address.

**Comment by codefromthecrypt** [comment]
apologies that this didn't work

**Comment by kirenjolly** [comment]
This mailmap for email was done to map the actual issue created from my another github account.
https://github.com/openzipkin-contrib/brave-ratpack/issues/14
And the PR raised to fix the bug is: 
https://github.com/openzipkin-contrib/brave-ratpack/pull/15
