### ISSUE TITLE
TraceContextHolder Class has to be Singleton

### ISSUE THREAD

**Issue by kirenjolly** [openzipkin-contrib/brave-ratpack#19]
### TraceContextHolder Class has to be Singleton

Multiple instance of the same class is found in the registries of the Current `Execution` object.
This causes `RatpackCurrentTraceContext.get()` function to return `null` context on creation of new spans. Hence forming separate traces.

![screenshot 7](https://user-images.githubusercontent.com/26733134/53120348-a52bc400-3577-11e9-9067-b6fc54b3bf1e.png)

**Comment by kirenjolly** [comment]
@adriancole @llinder @beckje01 Please take a look.

**Comment by llinder** [comment]
Thanks.  I would agree that this seems like a bug we should fix.  I have opened a PR https://github.com/openzipkin-contrib/brave-ratpack/pull/20 but still need to sort out proper test before it is merged.

**Comment by kirenjolly** [comment]
@llinder  Can you release a SNAPSHOT then for our local testing.

**Comment by llinder** [comment]
@kirenjolly I added some tests over the weekend and published a new release 2.4.1.  Mind checking to see if this resolves things for you?

**Comment by kirenjolly** [comment]
Sure will take a look. Thanks

**Comment by llinder** [comment]
I'm going to assume this issue has been resolved.  If not please reopen with comment and or tests showing whats failing.
